### ISSUE TITLE
既存生の登録機構

### ISSUE THREAD

**Issue by MogamiTsuchikawa** [SIT-DigiCre/digicore_v3_backend#45]
既存生と新入生を分けて登録

**Comment by Shimiiy** [comment]
今週の金曜日までに緊急連絡先を学生課に提出する必要があるので、幹部としてはこちらを優先で開発していただきたいです

**Comment by MogamiTsuchikawa** [comment]
今週の金曜か！では明日リリースできるようにしましょう
@ecto0310 Group機能、リリースいけそうですか？

**Comment by ecto0310** [comment]
@MogamiTsuchikawa 最低限の機能は完成してます(一覧、参加、脱退は可能になってます
